// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Test
*/
package message

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Test struct {
	Label            *string          `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32           `protobuf:"varint,2,opt,name=type,def=77" json:"type,omitempty"`
	Reps             []int64          `protobuf:"varint,3,rep,name=reps" json:"reps,omitempty"`
	Somebutton       *Test_Somebutton `protobuf:"group,4,req" json:"somebutton,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}

const Default_Test_Type int32 = 77

func (m *Test) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Test_Type
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetSomebutton() *Test_Somebutton {
	if m != nil {
		return m.Somebutton
	}
	return nil
}

type Test_Somebutton struct {
	Button           *string `protobuf:"bytes,5,req,name=button" json:"button,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test_Somebutton) Reset()         { *m = Test_Somebutton{} }
func (m *Test_Somebutton) String() string { return proto.CompactTextString(m) }
func (*Test_Somebutton) ProtoMessage()    {}

func (m *Test_Somebutton) GetButton() string {
	if m != nil && m.Button != nil {
		return *m.Button
	}
	return ""
}

func init() {
}
